### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by T0ng5** [syncsynchalt/illustrated-x25519#3]
"Alice's secret key - a 255-bit (~32-byte) random number"
"Bob's secret key - a 255-bit (~32-byte) random number"

Curve25519 uses 256-bit keys

**Comment by syncsynchalt** [comment]
It's actually more like a 251-bit key.  The peers will likely each generate a full 256-bit random number for efficiency, but five of those bits are then "clamped" to particular values:

- the highest order bit is set to 1
- the next highest order bit is set to 0
- the three lowest order bits are set to 0

See section 4.7 of [this PDF](https://martin.kleppmann.com/papers/curve25519.pdf) for more details, it's also in [djb's original paper](https://cr.yp.to/ecdh/curve25519-20060209.pdf) but I find the former explains it better.

I think I must have written "255-bit random number" because the keys go as high as `0x7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff8` but the reality is a little more nuanced.  I'll have a think about the best way to say this.

**Comment by syncsynchalt** [comment]
Pushed a fix for this (I went with 256-bits keys, like you suggested). Let me know if you spot anything else.
